SAMPLE_TRANSACTIONS = [
    {"date": "2026-01-01", "description": "SALARY CREDIT - BLUEORB TECHNOLOGIES", "amount": 85000, "type": "credit", "category": "salary"},
    {"date": "2026-01-01", "description": "RENT TRANSFER - BANGALORE LANDLORD", "amount": 22000, "type": "debit", "category": "transfer"},
    {"date": "2026-01-02", "description": "ZERODHA COIN MUTUAL FUND SIP", "amount": 5000, "type": "debit", "category": "investment"},
    {"date": "2026-01-02", "description": "UPI SWIGGY INSTAMART", "amount": 1240, "type": "debit", "category": "food"},
    {"date": "2026-01-03", "description": "UPI SWIGGY FOOD ORDER", "amount": 780, "type": "debit", "category": "food"},
    {"date": "2026-01-04", "description": "UPI ZOMATO DINNER", "amount": 920, "type": "debit", "category": "food"},
    {"date": "2026-01-05", "description": "AMAZON PRIME SUBSCRIPTION", "amount": 299, "type": "debit", "category": "subscription"},
    {"date": "2026-01-06", "description": "NETFLIX INDIA", "amount": 649, "type": "debit", "category": "subscription"},
    {"date": "2026-01-07", "description": "SPOTIFY INDIA", "amount": 119, "type": "debit", "category": "subscription"},
    {"date": "2026-01-08", "description": "LIC PREMIUM", "amount": 2400, "type": "debit", "category": "utilities"},
    {"date": "2026-01-09", "description": "UPI BIGBASKET GROCERIES", "amount": 2600, "type": "debit", "category": "food"},
    {"date": "2026-01-10", "description": "CULT FIT GYM MEMBERSHIP", "amount": 1500, "type": "debit", "category": "healthcare"},
    {"date": "2026-01-12", "description": "AUTO DEBIT CLOUD VAULT", "amount": 149, "type": "debit", "category": "subscription"},
    {"date": "2026-01-13", "description": "UPI NAMMA METRO", "amount": 500, "type": "debit", "category": "transport"},
    {"date": "2026-01-15", "description": "ATM CASH WITHDRAWAL", "amount": 3000, "type": "debit", "category": "atm"},
    {"date": "2026-01-16", "description": "UPI STAR BAZAAR", "amount": 1850, "type": "debit", "category": "food"},
    {"date": "2026-01-18", "description": "BESCOM ELECTRICITY BILL", "amount": 1450, "type": "debit", "category": "utilities"},
    {"date": "2026-01-20", "description": "MYNTRA CLOTHING", "amount": 4500, "type": "debit", "category": "shopping"},
    {"date": "2026-01-22", "description": "AUTO DEBIT DESIGN APP", "amount": 199, "type": "debit", "category": "subscription"},
    {"date": "2026-01-25", "description": "UPI SWIGGY FOOD ORDER", "amount": 640, "type": "debit", "category": "food"},
    {"date": "2026-01-28", "description": "AIRTEL POSTPAID", "amount": 999, "type": "debit", "category": "utilities"},
    {"date": "2026-02-01", "description": "SALARY CREDIT - BLUEORB TECHNOLOGIES", "amount": 85000, "type": "credit", "category": "salary"},
    {"date": "2026-02-01", "description": "RENT TRANSFER - BANGALORE LANDLORD", "amount": 22000, "type": "debit", "category": "transfer"},
    {"date": "2026-02-02", "description": "ZERODHA COIN MUTUAL FUND SIP", "amount": 5000, "type": "debit", "category": "investment"},
    {"date": "2026-02-02", "description": "UPI SWIGGY FOOD ORDER", "amount": 1180, "type": "debit", "category": "food"},
    {"date": "2026-02-03", "description": "UPI THIRD WAVE COFFEE", "amount": 480, "type": "debit", "category": "food"},
    {"date": "2026-02-04", "description": "UPI ZOMATO DINNER", "amount": 1060, "type": "debit", "category": "food"},
    {"date": "2026-02-05", "description": "AMAZON PRIME SUBSCRIPTION", "amount": 299, "type": "debit", "category": "subscription"},
    {"date": "2026-02-06", "description": "NETFLIX INDIA", "amount": 649, "type": "debit", "category": "subscription"},
    {"date": "2026-02-07", "description": "SPOTIFY INDIA", "amount": 119, "type": "debit", "category": "subscription"},
    {"date": "2026-02-08", "description": "LIC PREMIUM", "amount": 2400, "type": "debit", "category": "utilities"},
    {"date": "2026-02-10", "description": "UPI BIGBASKET GROCERIES", "amount": 3100, "type": "debit", "category": "food"},
    {"date": "2026-02-12", "description": "AUTO DEBIT CLOUD VAULT", "amount": 149, "type": "debit", "category": "subscription"},
    {"date": "2026-02-14", "description": "UPI OLA CABS", "amount": 780, "type": "debit", "category": "transport"},
    {"date": "2026-02-18", "description": "BESCOM ELECTRICITY BILL", "amount": 1520, "type": "debit", "category": "utilities"},
    {"date": "2026-02-19", "description": "CROMA ELECTRONICS", "amount": 8000, "type": "debit", "category": "shopping"},
    {"date": "2026-02-22", "description": "AUTO DEBIT DESIGN APP", "amount": 199, "type": "debit", "category": "subscription"},
    {"date": "2026-02-23", "description": "ATM CASH WITHDRAWAL", "amount": 2000, "type": "debit", "category": "atm"},
    {"date": "2026-02-26", "description": "UPI SWIGGY FOOD ORDER", "amount": 520, "type": "debit", "category": "food"},
    {"date": "2026-02-28", "description": "AIRTEL POSTPAID", "amount": 999, "type": "debit", "category": "utilities"},
    {"date": "2026-03-01", "description": "SALARY CREDIT - BLUEORB TECHNOLOGIES", "amount": 85000, "type": "credit", "category": "salary"},
    {"date": "2026-03-01", "description": "RENT TRANSFER - BANGALORE LANDLORD", "amount": 22000, "type": "debit", "category": "transfer"},
    {"date": "2026-03-02", "description": "ZERODHA COIN MUTUAL FUND SIP", "amount": 5000, "type": "debit", "category": "investment"},
    {"date": "2026-03-02", "description": "UPI SWIGGY FOOD ORDER", "amount": 1320, "type": "debit", "category": "food"},
    {"date": "2026-03-03", "description": "UPI SWIGGY INSTAMART", "amount": 950, "type": "debit", "category": "food"},
    {"date": "2026-03-04", "description": "UPI ZOMATO DINNER", "amount": 1120, "type": "debit", "category": "food"},
    {"date": "2026-03-05", "description": "AMAZON PRIME SUBSCRIPTION", "amount": 299, "type": "debit", "category": "subscription"},
    {"date": "2026-03-06", "description": "NETFLIX INDIA", "amount": 649, "type": "debit", "category": "subscription"},
    {"date": "2026-03-07", "description": "SPOTIFY INDIA", "amount": 119, "type": "debit", "category": "subscription"},
    {"date": "2026-03-08", "description": "LIC PREMIUM", "amount": 2400, "type": "debit", "category": "utilities"},
    {"date": "2026-03-11", "description": "UPI MORE SUPERMARKET", "amount": 2400, "type": "debit", "category": "food"},
    {"date": "2026-03-12", "description": "AUTO DEBIT CLOUD VAULT", "amount": 149, "type": "debit", "category": "subscription"},
    {"date": "2026-03-17", "description": "UPI NAMMA METRO", "amount": 500, "type": "debit", "category": "transport"},
    {"date": "2026-03-18", "description": "BESCOM ELECTRICITY BILL", "amount": 1380, "type": "debit", "category": "utilities"},
    {"date": "2026-03-21", "description": "ATM CASH WITHDRAWAL", "amount": 4000, "type": "debit", "category": "atm"},
    {"date": "2026-03-22", "description": "AUTO DEBIT DESIGN APP", "amount": 199, "type": "debit", "category": "subscription"},
    {"date": "2026-03-26", "description": "UPI SWIGGY FOOD ORDER", "amount": 760, "type": "debit", "category": "food"},
    {"date": "2026-03-28", "description": "AIRTEL POSTPAID", "amount": 999, "type": "debit", "category": "utilities"},
]

SAMPLE_PROFILE = {
    "name": "Priya Sharma",
    "age": 28,
    "city": "Bangalore",
    "occupation": "Software Engineer",
    "monthly_salary": 85000,
}
